export const TIER0_PHRASES = [
  "phoenix",
  "icarus",
  "juggernaut",
  "and then i realized",
  "and then i knew",
];

export const TIER1_PHRASES = [
  "rise above",
  "shattered dreams",
  "neon lights",
  "concrete jungle",
  "city of angels",
  "sin city",
  "broken dreams",
  "fire burns inside",
  "the fire in my soul",
  "we will rise",
  "can't go on without you",
  "whispers in the dark",
  "echoes of the night",
  "lost inside the silence",
  "gonna make it",
  "break free",
  "we're all in this together",
  "tomorrow it gets better",
  "gonna rise",
  "make it through the night",
  "heart of gold",
  "endless night",
  "dancing in the dark",
];

export const TIER2_PHRASES = [
  "you're everything",
  "nothing matters but you",
  "my everything",
  "forever and always",
];

export const ABSTRACT_NOUNS = [
  "pain",
  "soul",
  "destiny",
  "fate",
  "hope",
  "dreams",
  "dream",
  "love",
  "heart",
  "darkness",
  "light",
  "fire",
  "shadows",
  "echoes",
  "whispers",
  "silence",
  "forever",
  "eternity",
  "brokenness",
  "salvation",
  "grace",
  "void",
  "abyss",
  "night",
  "flame",
  "ashes",
];

export const CONCRETE_HINTS = [
  "door",
  "jacket",
  "whiskey",
  "nightstand",
  "rain",
  "windshield",
  "alarm",
  "shift",
  "pharmacy",
  "lease",
  "counter",
  "ring",
  "pawn",
  "amp",
  "dog",
  "ticket",
  "ashtray",
  "canyon",
  "porch",
  "key",
  "kitchen",
  "boots",
  "lot",
  "truck",
  "highway",
  "motel",
  "receipt",
  "voicemail",
  "bus",
  "train",
  "bar",
  "church",
  "pew",
  "bible",
  "amp",
  "string",
  "pick",
  "garage",
  "engine",
  "mileage",
  "zip",
  "county",
  "depot",
  "paystub",
  "lighter",
  "filter",
  "dashboard",
  "glovebox",
  "mailbox",
  "screen",
  "number",
];

export const AI_TELL_PAIRS = [
  ["echoes", "whispers"],
  ["heart", "screams"],
  ["soul", "cries"],
  ["dreams", "bleed"],
  ["hope", "flies"],
];

export const OVER_RHYME = [
  ["girl", "world"],
  ["fire", "higher"],
  ["pain", "again"],
  ["night", "light"],
  ["rain", "pain"],
];

export const COUNTRY_ALLOW = ["truck", "whiskey", "rain", "mama", "small town"];
export const METAL_ALLOW = ["darkness", "shadows", "eternal", "souls", "blood"];
export const HIPHOP_ALLOW = ["hustle", "grind", "streets", "ice", "rise"];
